In [1]:
import pandas as pd
import requests
import matplotlib.pyplot as plt
pd.options.display.float_format = '{:.1f}'.format

In [2]:
df = pd.read_csv('../Img_genoma/Copia de obra.csv', skiprows=1)

In [3]:
df.head()

,NOMBRE_O,TEC_1,TEC_2,ALTO,ANCHO,FONDO,PESO,VALOR_O,COL_PRED,COL_SEC,...,TAG_GENOMA_1,TAG_GENOMA_1.1,TAG_GENOMA_1.2,TAG_GENOMA_1.3,TAG_GENOMA_1.4,TAG_GENOMA_1.5,TAG_GENOMA_1.6,TAG_GENOMA_1.7,TAG_GENOMA_1.8,TAG_GENOMA_1.9
0,Invocando a un inmortal,Pintura,NaN,57,57,4.0,3,"$600,000",3,4,...,onírico,expresivo,pintura,color,escena,NaN,NaN,NaN,nan,nan
1,Si yo fuera princesa,Pintura,NaN,57,57,4.0,3,"$600,000",10,15,...,narrativo,figurativo,pintura,color,surreal,NaN,NaN,NaN,nan,nan
2,Se me hizo tarde,Pintura,NaN,57,57,4.0,3,"$600,000",9,13,...,figurativo,pintura,estudio,color,forma,NaN,NaN,NaN,nan,nan
3,Infancia,Medios Experimentales,Arte textil,70,30,4.0,250,"$1,500,000",5,1,...,tejido,pandemia,meditativo,ancestral,tecnología,NaN,NaN,NaN,nan,nan
4,Natura Viva 1,Dibujo,NaN,50,35,1.0,20,"$580,000",4,8,...,naturaleza,abstracción,gesto,color,figurativo,NaN,NaN,NaN,nan,nan

In [4]:
df.describe().T

                  count   mean    std  min  25%   50%    75%      max
ALTO              228.0  664.2 7996.9  0.0 30.0  50.0   70.0 120140.0
ANCHO             228.0   58.4   51.3  0.0 26.0  45.0   70.5    300.0
FONDO             169.0    7.4   29.7  0.0  2.0   3.0    4.0    300.0
PESO              228.0 1414.2 4060.4  0.0  5.0 416.0 1000.0  50000.0
COL_PRED          228.0    5.7    4.2  1.0  2.0   5.0    8.0     15.0
COL_SEC           228.0    6.7    4.6  1.0  3.0   6.0   12.0     15.0
FOTO_GEN            0.0    nan    nan  nan  nan   nan    nan      nan
VAL_L             207.0    3.0    1.3  1.0  2.0   3.0    4.0      5.0
URL_VIDEO_GENOMA    0.0    nan    nan  nan  nan   nan    nan      nan
TAG_GENOMA_1.8      0.0    nan    nan  nan  nan   nan    nan      nan
TAG_GENOMA_1.9      0.0    nan    nan  nan  nan   nan    nan      nan

In [5]:
df.columns

Index(['NOMBRE_O', 'TEC_1', 'TEC_2', 'ALTO', 'ANCHO ', 'FONDO', 'PESO',
       'VALOR_O', 'COL_PRED', 'COL_SEC', 'TEM_1', 'TEM_2', 'TEM_3',
       'URL_IMG_1', 'URL_IMG_2', 'URL_IMG_3', 'URL_IMG_4', 'URL_IMG_5',
       'URL_VIDEO', 'FECHA_CRE', 'FECHA_ING_O', 'TOKEN', 'FOTO_GEN', 'VAL_L',
       'VAL_E', 'URL_GENOMA_2', 'URL_GENOMA_2.1', 'URL_GENOMA_3',
       'URL_GENOMA_4', 'URL_GENOMA_5', 'URL_VIDEO_GENOMA', 'TAG_GENOMA_1',
       'TAG_GENOMA_1.1', 'TAG_GENOMA_1.2', 'TAG_GENOMA_1.3', 'TAG_GENOMA_1.4',
       'TAG_GENOMA_1.5', 'TAG_GENOMA_1.6', 'TAG_GENOMA_1.7', 'TAG_GENOMA_1.8',
       'TAG_GENOMA_1.9'],
      dtype='object')

In [6]:
df_url = df[['TOKEN', 'URL_IMG_1', 'URL_IMG_2', 'URL_IMG_3', 'URL_IMG_4', 'URL_IMG_5']]

In [7]:
name = []
for i in range(len(df_url)):
    temp1 = str(i) + '-genoma-' + (df.TOKEN.iloc[i])
    name.append(temp1)

In [8]:
df_url['name'] = name

<ipython-input-8-2ee42b9fd99e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_url['name'] = name

In [9]:
df_url = df_url.fillna(0)

In [10]:
df_url.head()

,TOKEN,URL_IMG_1,URL_IMG_2,URL_IMG_3,URL_IMG_4,URL_IMG_5,name
0,vy4cl0yxbr2r15e4h5imvy4cl0ykmrz5,https://api.typeform.com/responses/files/b6d9f...,https://api.typeform.com/responses/files/57edb...,0,0,0,0-genoma-vy4cl0yxbr2r15e4h5imvy4cl0ykmrz5
1,j3ezyt3hpqexn37w40j3ezytw9do8iss,https://api.typeform.com/responses/files/8dadb...,https://api.typeform.com/responses/files/90c62...,0,0,0,1-genoma-j3ezyt3hpqexn37w40j3ezytw9do8iss
2,3nhf4m5bot6h4o2xms03nhf4mu194m66,https://api.typeform.com/responses/files/c8eec...,https://api.typeform.com/responses/files/99959...,0,0,0,2-genoma-3nhf4m5bot6h4o2xms03nhf4mu194m66
3,owzlbphkinfc1iwdowzlb0yuzypn0qw3,https://api.typeform.com/responses/files/3bff6...,https://api.typeform.com/responses/files/d216a...,0,0,0,3-genoma-owzlbphkinfc1iwdowzlb0yuzypn0qw3
4,7bbs0fztb77orwjxo17bbs0fzbztf6o1,https://api.typeform.com/responses/files/6e9ea...,https://api.typeform.com/responses/files/4e1c1...,https://api.typeform.com/responses/files/57063...,https://api.typeform.com/responses/files/e6e97...,https://api.typeform.com/responses/files/3d4f7...,4-genoma-7bbs0fztb77orwjxo17bbs0fzbztf6o1

In [11]:
columns = ['URL_IMG_1', 'URL_IMG_2','URL_IMG_3', 'URL_IMG_4', 'URL_IMG_5']
for col in columns:    
    for url in range(len(df_url)):
        if not df_url.iloc[url][col] == 0:
            try:
                url_imagen = df_url.iloc[url][col] # El link de la imagen
                nombre_local_imagen = str(df_url.name.iloc[url] + '-' + str(col) + '.jpg')
                print(nombre_local_imagen)
                folder = 'Img/'
                imagen = requests.get(url_imagen).content
                with open(folder + nombre_local_imagen, 'wb') as handler:
                    handler.write(imagen)
            except:
                print('ERROR' + str(nombre_local_imagen))
        else:
            pass

200-genoma-p1xgnfo3gn55ulq3ogup1xgng1xwnxop-URL_IMG_1.jpg
201-genoma-31xqeglcfkt4c6yun331xqedrwj48431-URL_IMG_1.jpg
202-genoma-2m5rtackve35r172m5rtg46a05p5gk5x-URL_IMG_1.jpg
203-genoma-hl6zi27in56l9vjs7hl6z16ho7rn1axq-URL_IMG_1.jpg
204-genoma-1zmu1qn5u938rzrt21zmu1qowbhnt0x0-URL_IMG_1.jpg
205-genoma-dkrlzh4t1m5jl5dkrlyopun5d063je1y-URL_IMG_1.jpg
206-genoma-3rc8c1pufbg3a0jtx8gn3rc8c1pizar7-URL_IMG_1.jpg
207-genoma-4q4dwi0y0hm84hi8604q4n7c9o0y39pr-URL_IMG_1.jpg
208-genoma-kk64fp4ae1aig3r17kk64fpb9j9sqevk-URL_IMG_1.jpg
209-genoma-wn6dttq30qcer2mchwn6khvzzks5tw90-URL_IMG_1.jpg
210-genoma-gp9zkgyp1thoqg2s0gp9ctartoyuxahd-URL_IMG_1.jpg
211-genoma-seqc1t9h5lp3svgbopovseqcn5jzk5to-URL_IMG_1.jpg
212-genoma-hb5ugqqalu5thni1yahb5ngm2md35eoq-URL_IMG_1.jpg
213-genoma-wt1cwy3k1l2ve22rxqmq8gwt1cwy1w49-URL_IMG_1.jpg
214-genoma-xiljr4923mpwxkospixiljr43ipqgs2n-URL_IMG_1.jpg
215-genoma-mywsuvqd5gkcabw8ph9mmywsuviwg849-URL_IMG_1.jpg
216-genoma-vuh39oeuknzefedry4kvuh39u9fvrcpm-URL_IMG_1.jpg
217-genoma-3z5qvbguzr21l0eq9anv3z5qvb0oz6g7-URL_IMG_1.jpg
218-genoma-4ondf19ckcani0qhj0pd4ondf19cklni-URL_IMG_1.jpg
219-genoma-rwalm9asucs1gr2abd03rwalm9asm842-URL_IMG_1.jpg
220-genoma-sxsere84osbkd88rsxseredms1dj0a61-URL_IMG_1.jpg
221-genoma-lawajo3w99t7gqd9a48lawaj4oxe2g5k-URL_IMG_1.jpg
222-genoma-z71lvthyf2xgeppp6iji73z71lvte4t0-URL_IMG_1.jpg
223-genoma-dphc2s59j1amjo2aadphc2vxxfdkgijj-URL_IMG_1.jpg
224-genoma-2a6w008ci8qfx4a9v42a6wcn3d94vdze-URL_IMG_1.jpg
225-genoma-ipdd6mmanvepy6jmjr5zripdd6m73mko-URL_IMG_1.jpg
226-genoma-nzazvryd6u670uzvvnzagijffppndgi4-URL_IMG_1.jpg
227-genoma-4nawef022il25b7yf5ayn4nawef1aup2-URL_IMG_1.jpg
200-genoma-p1xgnfo3gn55ulq3ogup1xgng1xwnxop-URL_IMG_2.jpg
201-genoma-31xqeglcfkt4c6yun331xqedrwj48431-URL_IMG_2.jpg
202-genoma-2m5rtackve35r172m5rtg46a05p5gk5x-URL_IMG_2.jpg
203-genoma-hl6zi27in56l9vjs7hl6z16ho7rn1axq-URL_IMG_2.jpg
204-genoma-1zmu1qn5u938rzrt21zmu1qowbhnt0x0-URL_IMG_2.jpg
205-genoma-dkrlzh4t1m5jl5dkrlyopun5d063je1y-URL_IMG_2.jpg
206-genoma-3rc8c1pufbg3a0jtx8gn3rc8c1pizar7-URL_IMG_2.jpg
207-genoma-4q4dwi0y0hm84hi8604q4n7c9o0y39pr-URL_IMG_2.jpg
208-genoma-kk64fp4ae1aig3r17kk64fpb9j9sqevk-URL_IMG_2.jpg
209-genoma-wn6dttq30qcer2mchwn6khvzzks5tw90-URL_IMG_2.jpg
210-genoma-gp9zkgyp1thoqg2s0gp9ctartoyuxahd-URL_IMG_2.jpg
211-genoma-seqc1t9h5lp3svgbopovseqcn5jzk5to-URL_IMG_2.jpg
212-genoma-hb5ugqqalu5thni1yahb5ngm2md35eoq-URL_IMG_2.jpg
213-genoma-wt1cwy3k1l2ve22rxqmq8gwt1cwy1w49-URL_IMG_2.jpg
214-genoma-xiljr4923mpwxkospixiljr43ipqgs2n-URL_IMG_2.jpg
215-genoma-mywsuvqd5gkcabw8ph9mmywsuviwg849-URL_IMG_2.jpg
216-genoma-vuh39oeuknzefedry4kvuh39u9fvrcpm-URL_IMG_2.jpg
217-genoma-3z5qvbguzr21l0eq9anv3z5qvb0oz6g7-URL_IMG_2.jpg
218-genoma-4ondf19ckcani0qhj0pd4ondf19cklni-URL_IMG_2.jpg
219-genoma-rwalm9asucs1gr2abd03rwalm9asm842-URL_IMG_2.jpg
220-genoma-sxsere84osbkd88rsxseredms1dj0a61-URL_IMG_2.jpg
221-genoma-lawajo3w99t7gqd9a48lawaj4oxe2g5k-URL_IMG_2.jpg
222-genoma-z71lvthyf2xgeppp6iji73z71lvte4t0-URL_IMG_2.jpg
223-genoma-dphc2s59j1amjo2aadphc2vxxfdkgijj-URL_IMG_2.jpg
224-genoma-2a6w008ci8qfx4a9v42a6wcn3d94vdze-URL_IMG_2.jpg
225-genoma-ipdd6mmanvepy6jmjr5zripdd6m73mko-URL_IMG_2.jpg
226-genoma-nzazvryd6u670uzvvnzagijffppndgi4-URL_IMG_2.jpg
227-genoma-4nawef022il25b7yf5ayn4nawef1aup2-URL_IMG_2.jpg
202-genoma-2m5rtackve35r172m5rtg46a05p5gk5x-URL_IMG_3.jpg
210-genoma-gp9zkgyp1thoqg2s0gp9ctartoyuxahd-URL_IMG_3.jpg
212-genoma-hb5ugqqalu5thni1yahb5ngm2md35eoq-URL_IMG_3.jpg
213-genoma-wt1cwy3k1l2ve22rxqmq8gwt1cwy1w49-URL_IMG_3.jpg
214-genoma-xiljr4923mpwxkospixiljr43ipqgs2n-URL_IMG_3.jpg
215-genoma-mywsuvqd5gkcabw8ph9mmywsuviwg849-URL_IMG_3.jpg
217-genoma-3z5qvbguzr21l0eq9anv3z5qvb0oz6g7-URL_IMG_3.jpg
219-genoma-rwalm9asucs1gr2abd03rwalm9asm842-URL_IMG_3.jpg
220-genoma-sxsere84osbkd88rsxseredms1dj0a61-URL_IMG_3.jpg
221-genoma-lawajo3w99t7gqd9a48lawaj4oxe2g5k-URL_IMG_3.jpg
227-genoma-4nawef022il25b7yf5ayn4nawef1aup2-URL_IMG_3.jpg
201-genoma-31xqeglcfkt4c6yun331xqedrwj48431-URL_IMG_4.jpg
210-genoma-gp9zkgyp1thoqg2s0gp9ctartoyuxahd-URL_IMG_4.jpg
212-genoma-hb5ugqqalu5thni1yahb5ngm2md35eoq-URL_IMG_4.jpg
213-genoma-wt1cwy3k1l2ve22rxqmq8gwt1cwy1w49-URL_IMG_4.jpg
214-genoma-xiljr4923mpwxkospixiljr43ipqgs2n-URL_IMG_4.jpg
215-genoma-mywsuvqd5gkcabw8ph9mmywsuviwg849-URL_IMG_4.jpg
217-genoma-3z5qvbguzr21l0eq9anv3z5qvb0oz6g7-URL_IMG_4.jpg
219-genoma-rwalm9asucs1gr2abd03rwalm9asm842-URL_IMG_4.jpg
220-genoma-sxsere84osbkd88rsxseredms1dj0a61-URL_IMG_4.jpg
221-genoma-lawajo3w99t7gqd9a48lawaj4oxe2g5k-URL_IMG_4.jpg
223-genoma-dphc2s59j1amjo2aadphc2vxxfdkgijj-URL_IMG_4.jpg
225-genoma-ipdd6mmanvepy6jmjr5zripdd6m73mko-URL_IMG_4.jpg
226-genoma-nzazvryd6u670uzvvnzagijffppndgi4-URL_IMG_4.jpg
201-genoma-31xqeglcfkt4c6yun331xqedrwj48431-URL_IMG_5.jpg
210-genoma-gp9zkgyp1thoqg2s0gp9ctartoyuxahd-URL_IMG_5.jpg
212-genoma-hb5ugqqalu5thni1yahb5ngm2md35eoq-URL_IMG_5.jpg
213-genoma-wt1cwy3k1l2ve22rxqmq8gwt1cwy1w49-URL_IMG_5.jpg
214-genoma-xiljr4923mpwxkospixiljr43ipqgs2n-URL_IMG_5.jpg
215-genoma-mywsuvqd5gkcabw8ph9mmywsuviwg849-URL_IMG_5.jpg
217-genoma-3z5qvbguzr21l0eq9anv3z5qvb0oz6g7-URL_IMG_5.jpg
219-genoma-rwalm9asucs1gr2abd03rwalm9asm842-URL_IMG_5.jpg
220-genoma-sxsere84osbkd88rsxseredms1dj0a61-URL_IMG_5.jpg
221-genoma-lawajo3w99t7gqd9a48lawaj4oxe2g5k-URL_IMG_5.jpg
223-genoma-dphc2s59j1amjo2aadphc2vxxfdkgijj-URL_IMG_5.jpg
227-genoma-4nawef022il25b7yf5ayn4nawef1aup2-URL_IMG_5.jpg

In [12]:
url_imagen

'https://api.typeform.com/responses/files/5dad59b4f7cb96172d1d632bae32b8d2df16e833258d29a26ee092ddf9072a34/IMG_20210309_064443406.jpg'